/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RoutesRouteImport } from "./routes/routes"
import { Route as PlaygroundRouteImport } from "./routes/playground"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as KeysRouteImport } from "./routes/keys"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as KeysKeyIdRouteImport } from "./routes/keys/$keyId"
import { Route as ConfigRoutesRouteImport } from "./routes/config/routes"
import { Route as ConfigProvidersRouteImport } from "./routes/config/providers"
import { Route as ConfigAccountsRouteImport } from "./routes/config/accounts"

const RoutesRoute = RoutesRouteImport.update({
  id: "/routes",
  path: "/routes",
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: "/playground",
  path: "/playground",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: "/keys",
  path: "/keys",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const KeysKeyIdRoute = KeysKeyIdRouteImport.update({
  id: "/$keyId",
  path: "/$keyId",
  getParentRoute: () => KeysRoute,
} as any)
const ConfigRoutesRoute = ConfigRoutesRouteImport.update({
  id: "/config/routes",
  path: "/config/routes",
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigProvidersRoute = ConfigProvidersRouteImport.update({
  id: "/config/providers",
  path: "/config/providers",
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigAccountsRoute = ConfigAccountsRouteImport.update({
  id: "/config/accounts",
  path: "/config/accounts",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/keys": typeof KeysRouteWithChildren
  "/login": typeof LoginRoute
  "/playground": typeof PlaygroundRoute
  "/routes": typeof RoutesRoute
  "/config/accounts": typeof ConfigAccountsRoute
  "/config/providers": typeof ConfigProvidersRoute
  "/config/routes": typeof ConfigRoutesRoute
  "/keys/$keyId": typeof KeysKeyIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/keys": typeof KeysRouteWithChildren
  "/login": typeof LoginRoute
  "/playground": typeof PlaygroundRoute
  "/routes": typeof RoutesRoute
  "/config/accounts": typeof ConfigAccountsRoute
  "/config/providers": typeof ConfigProvidersRoute
  "/config/routes": typeof ConfigRoutesRoute
  "/keys/$keyId": typeof KeysKeyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/keys": typeof KeysRouteWithChildren
  "/login": typeof LoginRoute
  "/playground": typeof PlaygroundRoute
  "/routes": typeof RoutesRoute
  "/config/accounts": typeof ConfigAccountsRoute
  "/config/providers": typeof ConfigProvidersRoute
  "/config/routes": typeof ConfigRoutesRoute
  "/keys/$keyId": typeof KeysKeyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/keys"
    | "/login"
    | "/playground"
    | "/routes"
    | "/config/accounts"
    | "/config/providers"
    | "/config/routes"
    | "/keys/$keyId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/keys"
    | "/login"
    | "/playground"
    | "/routes"
    | "/config/accounts"
    | "/config/providers"
    | "/config/routes"
    | "/keys/$keyId"
  id:
    | "__root__"
    | "/"
    | "/keys"
    | "/login"
    | "/playground"
    | "/routes"
    | "/config/accounts"
    | "/config/providers"
    | "/config/routes"
    | "/keys/$keyId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeysRoute: typeof KeysRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RoutesRoute: typeof RoutesRoute
  ConfigAccountsRoute: typeof ConfigAccountsRoute
  ConfigProvidersRoute: typeof ConfigProvidersRoute
  ConfigRoutesRoute: typeof ConfigRoutesRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/routes": {
      id: "/routes"
      path: "/routes"
      fullPath: "/routes"
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/playground": {
      id: "/playground"
      path: "/playground"
      fullPath: "/playground"
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/keys": {
      id: "/keys"
      path: "/keys"
      fullPath: "/keys"
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/keys/$keyId": {
      id: "/keys/$keyId"
      path: "/$keyId"
      fullPath: "/keys/$keyId"
      preLoaderRoute: typeof KeysKeyIdRouteImport
      parentRoute: typeof KeysRoute
    }
    "/config/routes": {
      id: "/config/routes"
      path: "/config/routes"
      fullPath: "/config/routes"
      preLoaderRoute: typeof ConfigRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/config/providers": {
      id: "/config/providers"
      path: "/config/providers"
      fullPath: "/config/providers"
      preLoaderRoute: typeof ConfigProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/config/accounts": {
      id: "/config/accounts"
      path: "/config/accounts"
      fullPath: "/config/accounts"
      preLoaderRoute: typeof ConfigAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KeysRouteChildren {
  KeysKeyIdRoute: typeof KeysKeyIdRoute
}

const KeysRouteChildren: KeysRouteChildren = {
  KeysKeyIdRoute: KeysKeyIdRoute,
}

const KeysRouteWithChildren = KeysRoute._addFileChildren(KeysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeysRoute: KeysRouteWithChildren,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  RoutesRoute: RoutesRoute,
  ConfigAccountsRoute: ConfigAccountsRoute,
  ConfigProvidersRoute: ConfigProvidersRoute,
  ConfigRoutesRoute: ConfigRoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
